### ISSUE TITLE
Remove deprecated components and deps

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor-frontend#11]
# Goal

Remove deprecated components, routes and dependencies that are no longer in use in Trading Strategy's [`frontend`](https://github.com/tradingstrategy-ai/frontend).

When these changes are complete, the footprint / role of `trade-executor-frontend` will be reduced to that of an API abstraction layer for `trade-executor` APIs (along with various related helper functions).

## Background

See [**`frontend` › #231 EPIC: Strategy pages Design System 0.2 update**](https://github.com/tradingstrategy-ai/frontend/issues/231)

The above changes required us to re-evaluate the dependency graph between `frontend` and `trade-executor-frontend`. After considering various options, the team agreed on the following approach:

<table width="100%">
<thead>
<tr>
<th width="33%">Before update</th>
<th width="33%">After update</th>
<th width="33%">Possible future state</th>
</tr>
</thead>

<tbody>
<tr>
<td valign="top"><em>Deprecated / unused UI components</em></td>
<td valign="top"><em>Reduce footprint of trade-executor-frontend to just API abstraction layer</em></td>
<td valign="top"><em>Pull shared design-system components / CSS into separate repo</em></td>
<tr>

<td valign="top">
Bootstrap has been mostly eliminated from frontend.
<code>frontend</code> pages depends on a set of internal reusable design-system components and global CSS files (for colors, typography and some layout utility classes).
<code>trade-executor-frontend</code> still relies on Bootstrap 4, which does not work well with our design-system components and CSS files.
</td>

<td valign="top">
All UI components pulled into frontend.
This was deemed the simplest approach, allowing for various reusable UI elements that are common to both repos to be extracted to the same shared set of design-system-components.
<br><strong>Downside:</strong> the Trade Execution UI is no longer independent of frontend.
</td>

<td valign="top">
Extract all shared / reusable components back out of frontend into design-system repo.
<code>frontend</code> and <code>trade-executor-frontend</code> would both depend on <code>design-system</code>. This adds some complexity and overhead to the development lifecycle.
<br><strong>Upside:</strong> Trade Execution UI becomes fully independent of frontend (again).
</td>
</tr>

</tr>

<tr>
<td valign="top" align="center">
<img src="https://user-images.githubusercontent.com/35901/212381508-6a54d026-6dde-4da9-b3e3-1c04fdea5b2a.png" alt="Diagram: Before update">
</td>
<td valign="top" align="center">
<img src="https://user-images.githubusercontent.com/35901/212381715-0e2b1707-7ac5-4cbb-8d4b-9e7f4d194b4f.png" alt="Diagram: After update">
</td>
<td valign="top" align="center">
<img src="https://user-images.githubusercontent.com/35901/212381916-4a0ca1cb-6d58-4c3a-9ad1-d48dea977b9a.png" alt="Diagram: Future state">
</td>
</tr>
</tbody>
</table>

Now that the `frontend` changes have been completed, the deprecated components, routes and other UI dependencies in `trade-executor-frontend` should be removed.

In the future, we may choose to extract the common / shared UI components back out of `frontend` into the `design-system` repo. This would allow `trade-executor-frontend` to run independent of `frontend`.

## Tasks

- [x] remove routes (leave a vanilla home route)
- [x] remove all Svelte components under `src/lib`
- [x] remove unused helpers under `src/lib`
- [x] remove all unused `npm` dependencies
- [x] upgrade svelte related dependencies
- [x] remove bootstrap from `app.html`
- [x] update `README.md` (and any other docs)
- [x] make sure `npm run dev`, `npm run build` and `npm run package` still work
- [x] make sure `frontend` still works with these changes
- [x] publish `minor` version update (after review/merge)
